Addback mpw5 designs
The-OpenROAD-Project/OpenLane-MPW-CI pull request #52
Opened 2022-06-24 09:24 UTC by vijayank88

MPW6 roll over design commits of MPW5 restored again to keep track of source files.
```
riscduino_dcore
riscduino_qcore
mpw5_prga
mpw5_microwatt
mpw5_marmot_asic
```

2022-06-27 06:47 UTC, vijayank88 commented
@vvbandeira 
Can you please approve and merge this?

2022-06-27 15:40 UTC, vvbandeira requested changes

2022-06-27 15:40 UTC, vvbandeira commented on designs/README.md
> +    -   Executable CI Script: [mpw5_prga](../scripts/mpw5_prga) |
Should it be `mpw6_prga`?

2022-06-27 15:40 UTC, vvbandeira commented on designs/README.md
> +    -   Executable CI Script: [rdq_uart_i2c_usb_spi_top](../scripts/rdq_uart_i2c_usb_spi_top) |
`rdq_uart_i2c_usb_spi_top` vs `rdq_uart_i2cm_usb_spi_top`
The second is the correct name for the script folder

2022-06-28 05:59 UTC, vvbandeira approved these changes

2022-06-28 08:57 UTC, merged