MPW6 designs added
The-OpenROAD-Project/OpenLane-MPW-CI pull request #56
Opened 2022-06-28 13:06 UTC by vijayank88

Signed-off-by: vijayank88 <paruthi143@gmail.com>
Following MPW6 design added to CI:
```
SonarOnChip8
yonga-can-controller
seven_segments
pong-chip
ExperiarSoC
caravel_soc_now
mpw6_hyperram
openram_openmpw
```

2022-06-28 13:50 UTC, vvbandeira requested changes
Remove `scripts/SonarOnChip8/.setup-flow.sh.swp` and add `*.swp` to gitignore file to avoid committing in the future.

2022-06-28 20:36 UTC, vvbandeira approved these changes
Ok to merge if CI is green.

2022-06-29 10:32 UTC, vijayank88 commented
@vvbandeira 
Its a just counter module taking too long runtime. `counter_alperen` and `counter_eeuet`

Problem with `set ::env(PL_BASIC_PLACEMENT) 1`

Now its been removed. My local run completed quickly. Let see in CI, how it goes.

2022-06-30 16:15 UTC, vvbandeira approved these changes

2022-06-30 16:16 UTC, merged